//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilePropertiesBaselineGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>application/java-archive</string>\r\n  <string>application/msonenote</string" +
            ">\r\n  <string>application/msword</string>\r\n  <string>application/octet-stream</st" +
            "ring>\r\n  <string>application/pkix-crl</string>\r\n  <string>application/PowerShell" +
            "</string>\r\n  <string>application/rat-file</string>\r\n  <string>application/vnd.ap" +
            "ple.installer+xml</string>\r\n  <string>application/vnd.ms-excel</string>\r\n  <stri" +
            "ng>application/vnd.ms-excel.addin.macroEnabled.12</string>\r\n  <string>applicatio" +
            "n/vnd.ms-officetheme</string>\r\n  <string>application/vnd.ms-pki.seccat</string>\r" +
            "\n  <string>application/vnd.ms-powerpoint</string>\r\n  <string>application/vnd.ms-" +
            "word.template.macroEnabled.12</string>\r\n  <string>application/vnd.ms-wpl</string" +
            ">\r\n  <string>application/windows-library+xml</string>\r\n  <string>application/win" +
            "dows-search-connector+xml</string>\r\n  <string>application/x-compress</string>\r\n " +
            " <string>application/x-csh</string>\r\n  <string>application/x-ms-xbap</string>\r\n " +
            " <string>application/x-msdownload</string>\r\n  <string>application/x-sh</string>\r" +
            "\n  <string>application/x-shockwave-flash</string>\r\n  <string>application/x-troff" +
            "-man</string>\r\n  <string>application/x-x509-ca-cert</string>\r\n  <string>applicat" +
            "ion/x-zip-compressed</string>\r\n  <string>application/xml</string>\r\n  <string>app" +
            "lication/xml-dtd</string>\r\n  <string>text/javascript</string>\r\n  <string>text/sc" +
            "riptlet</string>\r\n  <string>text/x-component</string>\r\n  <string>text/x-ms-conta" +
            "ct</string>\r\n  <string>text/x-ms-iqy</string>\r\n  <string>text/x-ms-odc</string>\r" +
            "\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AutoComplete_MimeTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoComplete_MimeTypes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.386</string>\r\n  <string>.ascx</string>\r\n  <string>.ashx</string>\r\n  <stri" +
            "ng>.asmx</string>\r\n  <string>.aspx</string>\r\n  <string>.bat</string>\r\n  <string>" +
            ".bin</string>\r\n  <string>.cat</string>\r\n  <string>.cer</string>\r\n  <string>.chm<" +
            "/string>\r\n  <string>.class</string>\r\n  <string>.cmd</string>\r\n  <string>.com</st" +
            "ring>\r\n  <string>.config</string>\r\n  <string>.contact</string>\r\n  <string>.crl</" +
            "string>\r\n  <string>.crt</string>\r\n  <string>.der</string>\r\n  <string>.dev</strin" +
            "g>\r\n  <string>.dll</string>\r\n  <string>.dotm</string>\r\n  <string>.dotx</string>\r" +
            "\n  <string>.drv</string>\r\n  <string>.dtd</string>\r\n  <string>.eps</string>\r\n  <s" +
            "tring>.exe</string>\r\n  <string>.hlp</string>\r\n  <string>.htc</string>\r\n  <string" +
            ">.hxd</string>\r\n  <string>.hxh</string>\r\n  <string>.hxs</string>\r\n  <string>.hxw" +
            "</string>\r\n  <string>.iqy</string>\r\n  <string>.jar</string>\r\n  <string>.js</stri" +
            "ng>\r\n  <string>.jse</string>\r\n  <string>.library-ms</string>\r\n  <string>.lnk</st" +
            "ring>\r\n  <string>.man</string>\r\n  <string>.msc</string>\r\n  <string>.msh</string>" +
            "\r\n  <string>.msh1</string>\r\n  <string>.msh1xml</string>\r\n  <string>.msh2</string" +
            ">\r\n  <string>.msh2xml</string>\r\n  <string>.mshtml</string>\r\n  <string>.msi</stri" +
            "ng>\r\n  <string>.msp</string>\r\n  <string>.ocx</string>\r\n  <string>.odc</string>\r\n" +
            "  <string>.one</string>\r\n  <string>.onepkg</string>\r\n  <string>.pif</string>\r\n  " +
            "<string>.potm</string>\r\n  <string>.potx</string>\r\n  <string>.ppam</string>\r\n  <s" +
            "tring>.ppsm</string>\r\n  <string>.ppt</string>\r\n  <string>.pptm</string>\r\n  <stri" +
            "ng>.pptx</string>\r\n  <string>.ps1</string>\r\n  <string>.ps1xml</string>\r\n  <strin" +
            "g>.ps2</string>\r\n  <string>.ps2xml</string>\r\n  <string>.psc1</string>\r\n  <string" +
            ">.psc2</string>\r\n  <string>.rat</string>\r\n  <string>.reg</string>\r\n  <string>.re" +
            "sx</string>\r\n  <string>.scr</string>\r\n  <string>.searchconnector-ms</string>\r\n  " +
            "<string>.sfc</string>\r\n  <string>.shs</string>\r\n  <string>.sldm</string>\r\n  <str" +
            "ing>.swf</string>\r\n  <string>.thmx</string>\r\n  <string>.vb</string>\r\n  <string>." +
            "vba</string>\r\n  <string>.vbe</string>\r\n  <string>.vbs</string>\r\n  <string>.vxd</" +
            "string>\r\n  <string>.wmf</string>\r\n  <string>.wpl</string>\r\n  <string>.ws</string" +
            ">\r\n  <string>.wsc</string>\r\n  <string>.wsf</string>\r\n  <string>.wsh</string>\r\n  " +
            "<string>.xbap</string>\r\n  <string>.xla</string>\r\n  <string>.xlam</string>\r\n  <st" +
            "ring>.xll</string>\r\n  <string>.xlm</string>\r\n  <string>.xlsm</string>\r\n  <string" +
            ">.xlsx</string>\r\n  <string>.xltm</string>\r\n  <string>.xltx</string>\r\n  <string>." +
            "xlv</string>\r\n  <string>.xsd</string>\r\n  <string>.zip</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection AutoComplete_FileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoComplete_FileExtensions"]));
            }
        }
    }
}
